Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AspNetCoreWorld.Models
{
    public class Trip
    {
        public int Id { get; set; }
        public string Name{ get; set; }
        public DateTime DateCreated { get; set; }
        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }

    }
}

ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AspNetCoreWorld.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        public string Name {get;set;}

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(4096, MinimumLength = 10)]
        public string Message { get; set; }
    }
}

ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AspNetCoreWorld.ViewModels
{
    public class TripViewModel
    {
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }
        public DateTime DateCreated { get; set; } = DateTime.UtcNow;
    }
}

Controllers/Api/TripsController.cs
using AspNetCoreWorld.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AspNetCoreWorld.ViewModels;
using AutoMapper;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace AspNetCoreWorld.Controllers.Api
{
    //[Authorize]
    [Route("api/trips")]
    public class TripsController : Controller
    {
        private IWorldRepository _repository;
        private ILogger<TripsController> _logger;

        public TripsController(IWorldRepository repository, ILogger<TripsController> logger)
        {
            _logger = logger;
            _repository = repository;
        }

        [HttpGet("")]
        public IActionResult Get()
        {
            try
            {
                var result = _repository.GetTripsByUsername(this.User.Identity.Name);

                Console.WriteLine("----------------------------");
                foreach (var vr in result)
                {
                    Console.WriteLine($"Name: {vr.Name}");
                    foreach (var st in vr.Stops)
                    {
                        Console.WriteLine($"ID: {st.Id}, stop name:{st.Name}");
                    }
                }
                Console.WriteLine("----------------------------");
                return Ok(Mapper.Map<IEnumerable<TripViewModel>>(result));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to get all trips: {0}", ex);
                return BadRequest(ex.Message);
            }
        }

        [HttpPost("")]
        public async Task<IActionResult> Post([FromBody]TripViewModel trip)
        {
            if(ModelState.IsValid)
            {
                // save data in dataBase
                var newTrip =  Mapper.Map<Trip>(trip);

                newTrip.UserName = User.Identity.Name;

                _repository.AddTrip(newTrip);

                if (await _repository.SaveChangesAsync())
                {
                    return Created($"api/trips/{trip.Name}", Mapper.Map<TripViewModel>(newTrip));
                }
                else
                {
                    return BadRequest("Failed to save changes to DataBase.");
                }
            }

            return BadRequest("Failed to save the trip.");
        }

    }
}

Controllers/Web/AppController.cs
using AspNetCoreWorld.Models;
using AspNetCoreWorld.Services;
using AspNetCoreWorld.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AspNetCoreWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;
        private IWorldRepository _repository;
        private ILogger<AppController> _logger;

        public AppController(IMailService mailService, 
            IConfigurationRoot config, 
            IWorldRepository repository,
            ILogger<AppController> logger)
        {
            _mailService = mailService;
            _config = config;
            _repository = repository;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Trips()
        {
            try
            {
                // var data = _repository.GetAllTrips();

                //return View(data);
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to get Trips in Index page:{ex.Message}");
                return Redirect("/error");
            }
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com"))
            {
                //ModelState.AddModelError("Email", "We don't support AOL addresses");
                ModelState.AddModelError("", "We don't support AOL addresses");
            }

            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From TheWorld", model.Message);

                ModelState.Clear();

                ViewBag.UserMessage = "Message Sent";
            }

            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

Views/App/About.cshtml
@{ 
    ViewBag.Title = "About page";
}

<h2>About my projects ))))</h2>

Views/App/Contact.cshtml
@model AspNetCoreWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "About page";
}

@section scripts {
<script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script type="text/javascript" src="~/lib/jquery-validation-unobtrusive/src/jquery.validate.unobtrusive.js"></script>
}

<h2>Contacts Me</h2>
<div class="row">
    <div class=" col-md-6 col-md-offset-3">
        <form method="post" class="form-group">
            
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name"  class="form-control" />
                    <span asp-validation-for="Name" class="text-muted"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input type="email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-muted"></span>
                </div>
                <div class="form-group">
                    <label >Form</label>
                    <textarea cols="40" rows="4" class="form-control">

                    </textarea>
                </div>
            <div>
                <a asp-controller="#" asp-action="#" class="btn btn-default ">Cancel</a>
                <input type="submit" value="Send Message" class="btn btn-info " />
            </div>
        </form>
    </div>
</div>

Views/App/Index.cshtml
@model IEnumerable<AspNetCoreWorld.Models.Trip>
@{
    ViewBag.Title = "Home Page";
}

<div class="row" >
   
    <div class="col-md-12">
        <h1>Welcome to the World.</h1>
        <p>This application will allow you to plan world trips</p>
        <a asp-controller="App" asp-action="trips" class="btn btn-lg btn-success">View my trips</a>
    </div>

</div>

Views/App/Trips.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section Scripts {
    <script src="~/lib/underscore/underscore.js"></script>
    <script src="~/lib/angular/angular.js"></script>
    <script src="~/lib/angular-route-1.5.7/package/angular-route.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    <script src="~/lib/gmaps/gmaps.js"></script>
    <script src="~/lib/travelMap/travelmap.js"></script>    
    <script src="~/js/app-trips.js"></script>
    <script src="~/js/tripsController.js"></script>
    <script src="~/js/simpleControls.js"></script>
    <script src="~/js/tripEditorController.js"></script>
    

}

<div class="row" ng-app="app-trips">

    <div ng-view></div>

    
</div>